# Constants for Hannibal Script Parsing

WHOLE_LINE_KILLERS = [
    "Hannibal", "TEASER", "ACT ONE", "ACT TWO", "ACT THREE", "ACT FOUR", "ACT FIVE", "ACT SIX",
    "END OF ACT ONE", "END OF ACT TWO", "END OF ACT THREE", "END OF ACT FOUR", "END OF ACT FIVE",
    "END OF TEASER", "FADE IN:", "FADE OUT.", "FADE TO BLACK.", "PROLOGUE", "CUT TO:",
    "FADE TO:", "DISSOLVE TO:", "SMASH TO:", "SMASH TO BLACK.", "MATCH CUT TO:", "TIME CUT TO:", "JUMP CUT TO:",
    "CONTINUED", "OMITTED", "END OF SHOW", "END OF ACT", "END OF EPISODE", "THE END", "FINAL SHOOTING SCRIPT",
    "FINAL DRAFT", "Collated", "WHITE REVISIONS", "BLUE", "PINK", "YELLOW",
    "GREEN", "GOLDENROD", "WHITE", "REVERSE ANGLE", "CLOSE-UP", "NEW ANGLE",
    "HIGH ANGLE", "POP WIDE", "ON THE FLOOR", "POST CREDITS", "END OF SEASON THREE!",
    "A PIXELATED DARKNESS", "THE TELEPHONE MATRIX", "THE MOUTHPIECE",
    "A STILL OF WILL GRAHAM", "A SIGN", "UTTER DARKNESS", "A RECORD NEEDLE",
    "A RIBBON OF CELLULOID", "A SPINNING SPROCKET WHEEL", "A RADIANT VISION",
    "A FULL MOON", "A HALF MOON", "A MOON-SHAPED HOLE", "A SMASHED MIRROR",
    "A TRANSPARENT VESSEL", "THE DRAGON'S WINGS", "A CAGE",
    "Written by", "Created by", "Directed by", "Story by", "Teleplay by", "Based on the characters", 
    "Based on the novel", "Production Draft", "Shooting Script",
    "Executive Producer", "Executive Producers", "PRODUCED BY", "Co-Executive Producer",
    "Associate Producer", "Consulting Producer", "Staff Writer",
    "PROPERTY OF:", "GAUMONT", "CHISWICK", "ALL RIGHTS RESERVED",
    "NO PORTIONS OF THIS SCRIPT", "PERFORMED, OR REPRODUCED", "WRITTEN CONSENT",
    "SCRIPT MAY BE", "QUOTED, OR PUBLISHED"
]

DYNAMIC_KILLERS = [
    # S3 specific mechanical/primal sounds
    r"^\s*(?:FWUM|CLICK|BLAM|WHOOSH|CRASH|BANG|SMASH|KLANG|K’CHUK|RING|PLIP|WHAM|P’KEE|PFFT|KLAXON|BUZZ|P'KEET|SHLUCK|PWUM|PLOP|ZAP|SHUNK|FWOOM|SCRITCH|KA-CHOO|BING-BONG|K-SHH+|FWUMMP|THWUB|KERSHICK|SLKGHHH|WHACK|THUNK|BARP|P-KEE|CH-CHUNK|WOOMPF)(?:\.|\s)*$",
    # Repeating SFX patterns
    r"^\s*(?:SLAM|CHOP|PLIP|PWUM|FWUP|BANG|THWUB|BLEEP|EEK)(?:[-\.\s]+(?:SLAM|CHOP|PLIP|PWUM|FWUP|BANG|THWUB|BLEEP|EEK))+\s*$",
    r"^\s*FADE (?:IN|OUT|TO|THROUGH):?",
    r"^\s*(?:CUT|SMASH CUT|BACK|MATCH CUT|TIME CUT|QUICK POP|SMASH BACK|HARD CUT|FLASH CUT|QUICK MATCH CUT|SWIPE) TO:?",
    r"^\s*DISSOLVE TO:?",
    r"^\s*(?:WIDENING|REVERSING|PUSHING|PULLING|PANNING|TILTING|TRACKING|CRANE|DOLLY)\b",
    # Footer filtering
    r"HANNIBAL\s+Ep\.\s+#\d+.*",
    r"\d{2}/\d{2}/\d{2}\s+\d+\.?\s*$",
    r"^\s*\d+\.\s*$",
    r"^\d+\.$",  # Page numbers like "1."
    r"^Hannibal\s+#", # Header junk "Hannibal #303"
    r"\d{1,2}/\d{1,2}/\d{2,4}", # Dates
    r"^\(CONTINUED\)$",
    r"^\s*©", r"^\s*\(c\)", r"^\s*\u00a9",
    r"^\s*[0-9]+$", # Isolated page numbers
    r"^\s*Bryan Fuller", r"^\s*Thomas Harris", r"^\s*David Slade", r"^\s*Steve Lightfoot",
    r"^\s*Tim Hunter", r"^\s*Guillermo Navarro", r"^\s*Michael Rymer",
    r"^\s*Chris Brancato", r"^\s*Jesse Alexander", r"^\s*Martha De Laurentiis"
]

PARTIAL_REMOVERS = [
    "(CONT'D)", "(CONT’D)", "(cont'd)", "(cont’d)", "(V.O.)", "(O.S.)", "(O.C.)",
    "(pre-lap)", "(into phone)", "(then)", "(MORE)", "(stunned)", "(whispers)",
    "(calling out)", "(intense)", "(pointing)", "(distorted, dreamlike)",
    "(re: the food)", "(re: the herbs)", "(re: the picture)", "(re: the lens)",
    "(re: the pigs)", "(re: the lunchbox)", "(re: the thermos)",
    "(not bitchy)", "(smiles and it's lovely)", "(almost inaudible)", "...", 
    "we --", "We are--", "we are--", "we are --", "We are --",
    "A CHYRON tells us", "A CHYRON", "RE-USE EP 101", "PRESENT", "FLASHBACK",
    "OMNISCIENT P.O.V.", "WILL’S P.O.V.", "WILL'S P.O.V.", "GEORGIA’S P.O.V.",
    "LONE MAN’S P.O.V.", "ABIGAIL’S P.O.V.", "JACK'S P.O.V.", "WILL’S FEVERISH P.O.V.",
    "ALANA’S POV", "INTERCUT WITH:", "WILL IS HALLUCINATING.", "STOCK FOOTAGE",
    "WILL GRAHAM'S BED", "THE SHADOWY TREES", "FIRELIGHT", "FLASH FORWARD",
    "A PENDULUM", "RETRO-WILL", "RETRO-HANNIBAL", "NOW-WILL", "THE MIRROR",
    "REALITY", "DREAM STATE", "MATCH TO:", "TRANSITION TO:", "SWIPE TO BLACK."
]

PROMOTION_BLACKLIST = [
    "HOBBS", "GRAHAM", "LECTER", "CRAWFORD", "BLOOM", "KATZ", "ZELLER", "PRICE", "LOUNDS",
    "GIDEON", "CHILTON", "LASS", "SUTCLIFFE", "MADCHEN", "BOYLE", "BUDISH", "SUMMERS",
    "CARRUTHERS", "SHELL", "STAG", "PENDULUM", "WINSTON", "DOE", "PILLS", "LABEL", "GUN",
    "REVEAL", "CAMERA", "CLOSE ON", "ON WILL", "ON HANNIBAL", "ON JACK", "ON ALANA",
    "A GLASS OF WATER", "THE ALARM CLOCK", "A PICTURE", "THE MORGUE",
    "A SEA URCHIN", "A BEAUTIFUL PIECE", "A TASTEFULLY-ORNATE", "A LARYNGOSCOPIC VIEW",
    "THE STRING SECTION", "THE MISSING INTESTINES", "A KITCHEN CENTRIFUGE",
    "A SNOWY SKY", "A HORRIBLE EYE", "A PAIR OF EYES", "THE BED OVERTURNS",
    "A RAINBOW TROUT", "UNDER THE BED", "A ROW OF CORN", "THE HUMAN MURAL",
    "THE MISSING LEG", "A BEAUTIFUL PLATE", "A SUDDEN PIERCING", "A SLOW SWINGING",
    "THE WENDIGO MAN STAG", "A CUT-GLASS PERFUME", "A BOILING FROTH", "A MAN'S ANGUISHED EYE",
    "A MAN'S FACE", "A PANEL TRUCK", "A SUDDEN LOUD BARKING", "A RIVULET OF BLOOD",
    "A BOOK COVER", "A CAR'S FRONT WHEEL", "A HONEY BEE", "A MAN'S CORPSE",
    "A SMOKE-BLACKENED FACE", "A BLUE SPARK", "A SOFT GOLDEN GLEAM", "A PADDED ENVELOPE",
    "THE BUTCHER BLOCK", "THE MAIN TELESCOPE", "THE REVERSE SIDE", "THE LABYRINTH",
    "A HARD, SOMBER CHORD", "A SOMBER REFRAIN", "A RECENTLY-DUG GRAVE", "A LONG BONE",
    "A SHEET-COVERED BODY", "A PEN SCRAWLS", "A HARPSICHORD NOTE", "A HUGE BONFIRE",
    "A HUNCHED, POWERFUL SILHOUETTE", "SPLAYED PAWS", "A FLASH OF CLAWS", "A FLASH OF FANGS",
    "A DISTORTED MAN", "A SINGLE BRIGHT OBJECT", "A DISEMBODIED VOICE", "A FANGED RESIN MUZZLE",
    "THE DIRE WOLF CRANIUM", "A SHADOW GROWS FAST", "A RIFLE", "A SHEATHED FILLET KNIFE",
    "A WAX PAPER-WRAPPED PACKAGE", "THE SUCKLING PIG", "AN INDUSTRIAL FREEZER",
    "A DESK", "A RACK OF LARGE GLASS", "A ROBIN", "A RAT", "AN INTENSE YOUNG MAN",
    "A CAR'S FRONT WHEEL", "A PARTY CROWD", "A BEAUTIFUL WOMAN", "A RUSHING TAP",
    "AN EMPTY CHAIR", "A POLICE CONSTABLE", "A CCTV CAMERA", "A DYING MAN",
    "A MAN IN HER SHOWER", "A TRUCK'S FRONT WHEEL", "A FALLING TEACUP", "SNOW",
    "SPOTS OF BLOOD", "THE WILDIGO", "A DOOR", "SHARDS OF PORCELAIN", "A WHITE SHEET",
    "THE BODY'S BACK", "THE DOCTOR'S NEEDLE TIP", "A FINAL LENGTH OF THREAD",
    "DUST MOTES", "CASTLE LECTER", "MISCHA LECTER", "A SEVERED ARM", "A HANDFUL OF SALT",
    "A PRECISION KITCHEN BLADE", "A PLATTER OF SKEWERS", "A BOTTLE OF WINE",
    "A SCOLD'S BRIDLE", "A BODY OF WATER", "A SNAIL", "A BURLAP SACK", "PHEASANT MEAT",
    "A CONTACT LENS", "A LAYER OF MAKEUP", "A SAUCER OF BLOOD", "A WINE BOTTLE",
    "A WINEGLASS", "A TRANSPARENT VESSEL", "A FULL MOON", "A HALF MOON",
    "A MOON-SHAPED HOLE", "A GLASS CUTTER", "A SMASHED MIRROR", "A BATHROOM GLASS",
    "A TELEPHONE", "A TELEPHONE RECEIVER", "TRAIN TRACKS", "TRAIN CARS",
    "A FIREFLY LARVA", "A RIPPLE OF WATER", "THE COLLAR", "THE TIE",
    "A BUBBLING SOUP POT", "A SCRIM OF CHEESECLOTH", "A CLEAR ASPIC", "A PENCIL",
    "A PENCIL SKETCH", "A STREAM OF COFFEE", "THE WOODCARVING", "A STRIP OF LIGHT",
    "A VENTILATOR", "THE EEL", "A TRUCK'S FRONT WHEEL", "A SAUCER OF BLOOD",
    "A MEDICINE VIAL", "AN EXTERNAL FIXATION", "A METAL SIGN", "THE NIGHT SKY",
    "A PIXELATED DARKNESS", "THE MOUTHPIECE", "A STILL OF WILL", "A VASE",
    "A PROJECTOR LENS", "A SCREEN", "A COLORLESS VISTA", "THE YELLOW PADDED ENVELOPE",
    "A SINGLE LIP", "THE CITY FOUNTAIN", "A RIBBON OF CELLULOID", "A SPINNING SPROCKET",
    "A MATCH", "A BURNING MATCH HEAD", "A BODY HOIST", "A BLACK WOMAN", "A SHADOW",
    "A MASK", "A VEHICLE'S ENGINE", "THE CLOCK", "A BOTTLE OF AMMONIA", "A TRIPOD",
    "THE VIDEO CAMERA", "A COFFIN", "A FUNERAL DIRECTOR", "A BUCK KNIFE BLADE",
    "THE MAJESTIC TATTOO", "THE ALTAR", "A LONE DIVA", "A LURID NEW YORK POST",
    "A CHUNK OF MASONRY", "A SAUCER OF BLOOD", "A GREAT LEDGER", "A CLIPPING"
]
